<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE GamesCatalog [
<!ELEMENT GamesCatalog (header,producers,gameEngines,publishers,Ratings,platforms,genres,games)>

	<!ELEMENT header (titleOfProject,description,authors,modificationDate,university)>
		<!ELEMENT titleOfProject (#PCDATA)>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT authors (student+)>
			<!ELEMENT student (firstName,lastName,index)>
				<!ELEMENT firstName (#PCDATA)>
				<!ELEMENT lastName (#PCDATA)>
				<!ELEMENT index (#PCDATA)>
		<!ELEMENT modificationDate (#PCDATA)>
		<!ELEMENT university (#PCDATA)>
		
	<!ELEMENT producers (producer+)>
		<!ELEMENT producer (companyName,foundationDate,sharePrice,headquarters)>
		<!ATTLIST producer 
			producerID ID #REQUIRED>
			<!ELEMENT companyName (#PCDATA)>
			<!ELEMENT foundationDate (#PCDATA)>
			<!ELEMENT sharePrice (#PCDATA)>
			<!ATTLIST sharePrice 
				currency  (USD|PLN|EURO) "USD">
			<!ELEMENT headquarters (#PCDATA)>
			
	<!ELEMENT gameEngines (engine+)>
		<!ELEMENT engine (name,company)>
		<!ATTLIST engine
			engineID ID #REQUIRED
			programmingLanguage CDATA #IMPLIED>
			<!ELEMENT name (#PCDATA)>
			<!ELEMENT company (#PCDATA)>
			
	<!ELEMENT publishers (publisher+)>
			<!ELEMENT publisher (publisherName)>
			<!ATTLIST publisher 
				publisherID ID #REQUIRED>
				<!ELEMENT publisherName (#PCDATA)>
				
	<!ELEMENT Ratings (Rating+)>
		<!ELEMENT Rating (#PCDATA)>
		<!ATTLIST Rating 
			ratingID (A|M|T|E|EC) #REQUIRED>
			
	<!ELEMENT platforms (platform+)>
		<!ELEMENT platform (#PCDATA)>
		<!ATTLIST platform 
			platformID (PC|PS4|XBOX|Multi) #REQUIRED>
			
	<!ELEMENT genres (genre+)>
		<!ELEMENT genre (#PCDATA)>
		<!ATTLIST genre 
			genreID (RPG|FPS|Stealth|RTS|Action) #REQUIRED>
			
	<!ELEMENT games (game*)>
		<!ELEMENT game (title,description,premierPrice,premierDate,metariticRate,cover)>
		<!ATTLIST game
			producerID IDREF #REQUIRED
			engineID IDREF #REQUIRED
			publisherID IDREF #REQUIRED
			ratingID IDREF #REQUIRED
			platformID IDREF #REQUIRED
			genreID IDREF #REQUIRED>
			<!ELEMENT title (#PCDATA)>
			<!ELEMENT description (#PCDATA)>
			<!ELEMENT premierPrice (#PCDATA)>
				<!ATTLIST premierPrice
					currency (USD|PLN|EURO) "USD">
			<!ELEMENT premierDate (#PCDATA)>
			<!ELEMENT metariticRate (metascore,userScore,numberOfVotes)>
				<!ELEMENT metascore (#PCDATA)>
				<!ELEMENT userScore (#PCDATA)>
				<!ELEMENT numberOfVotes (#PCDATA)>
				<!ATTLIST cover 
					src CDATA #REQUIRED>
]>

<GamesCatalog>
	<header>
		<titleOfProject>Katalog gier</titleOfProject>
		<description>Katalog zawierający najpopularniejsze gry ostatniej dekady!</description>
		<authors>
			<student>
				<firstName>Juliusz</firstName>
				<lastName>Gąsecki</lastName>
				<index>210184</index>
			</student>
			<student>
				<firstName>Bartosz</firstName>
				<lastName>Stempień</lastName>
				<index>210327</index>
			</student>
		</authors>
		<modificationDate>17.03.2019</modificationDate>
		<university>Politechnika Łódzka Wydział Fizyki Technicznej, Informatyki i Matematyki Stosowanej</university>
	</header>
	
	<producers>
		<producer producerID="BW">
			<companyName>BioWare</companyName>
			<foundationDate>placeholder</foundationDate>
			<sharePrice currency="USD">98,36 </sharePrice>
			<headquarters>placeholder</headquarters>	
		</producer>
		<producer producerID="CDP">
			<companyName>CD Project Red</companyName>
			<foundationDate>placeholder</foundationDate>
			<sharePrice currency="USD">placeholder</sharePrice>
			<headquarters>placeholder</headquarters>	
		</producer>
		<producer producerID="Bethesda">
			<companyName>Bethesda Softworks</companyName>
			<foundationDate>placeholder</foundationDate>
			<sharePrice currency="USD">placeholder</sharePrice>
			<headquarters>placeholder</headquarters>	
		</producer>
		<producer producerID="CD">
			<companyName>Crystal Dynamics</companyName>
			<foundationDate>placeholder</foundationDate>
			<sharePrice currency="USD">placeholder</sharePrice>
			<headquarters>placeholder</headquarters>	
		</producer>
		<producer producerID="Ubisof">
			<companyName>Ubisof</companyName>
			<foundationDate>placeholder</foundationDate>
			<sharePrice currency="USD">placeholder</sharePrice>
			<headquarters>placeholder</headquarters>	
		</producer>
		<producer producerID="Activision">
			<companyName>Activision Inc.</companyName>
			<foundationDate>placeholder</foundationDate>
			<sharePrice currency="USD">placeholder</sharePrice>
			<headquarters>placeholder</headquarters>	
		</producer>
		<producer producerID="Dice">
			<companyName>EA Digital Illusions Creative Entertainment</companyName>
			<foundationDate>placeholder</foundationDate>
			<sharePrice currency="USD">placeholder</sharePrice>
			<headquarters>placeholder</headquarters>	
		</producer>
	</producers>
	
	<gameEngines>
		<engine engineID = "Frostbite" programmingLanguage = "C++">
			<name>Frostbite</name>
			<company>EA Dice</company>
		</engine>
		
		<engine engineID = "FEngine" programmingLanguage = "C++">
			<name>Foundation engine</name>
			<company>Crystal Dynamics</company>
		</engine>
		
		<engine engineID = "EclipseEngine" programmingLanguage = "C++">
			<name>Eclipse engine</name>
			<company>EclipseOrigins</company>
		</engine>
		<engine engineID = "Unreal" programmingLanguage = "C++">
			<name>Unreal engine</name>
			<company>Epic Games</company>
		</engine>
	</gameEngines>
	
	<publishers>
		<publisher publisherID = "EA">
			<publisherName>Electronic Arts</publisherName>
		</publisher>
		<publisher publisherID = "SE">
			<publisherName>Square Enix</publisherName>
		</publisher>
	</publishers>
	
	<Ratings>
		<Rating ratingID = "A">Adults Only</Rating>
		<Rating ratingID = "M">Mature</Rating>
		<Rating ratingID = "T">Teen</Rating>
		<Rating ratingID = "E">Everyone</Rating>
		<Rating ratingID = "EC">Early Childhood</Rating>
	</Ratings>
	
	<platforms>	
		<platform platformID = "PC">PC</platform>
		<platform platformID = "PS4">Play Station 4</platform>
		<platform platformID = "XBOX">XBOX One</platform>
		<platform platformID = "Multi">Multiplatformowe</platform>
	</platforms>
	<genres>
		<genre genreID = "RPG">Role Playing Game </genre>
		<genre genreID = "FPS">First Person Shooter </genre>
		<genre genreID = "Stealth">Skradanka </genre>
		<genre genreID = "RTS">Strategia czasu rzeczywistego </genre>
		<genre genreID = "Action">Gra akcji </genre>
	</genres>
	<games>
		<game producerID = "Dice" engineID = "Frostbite" publisherID = "EA" ratingID = "M" platformID = "Multi" genreID="FPS">
			<title>Battlefield 5</title>
			<description> Enter mankind's greatest conflict with Battlefield 5 as the series goes back to its roots with a never-before-seen portrayal of World War 2. Lead your squad to victory with new ways to turn the battlefield to your advantage. Assemble your Company of customized soldiers, weapons, and vehicles then take them on an epic journey through the Tides of War. Experience the most intense, immersive Battlefield yet. You will never be the same.</description>
			<premierPrice currency = "PLN">249.90</premierPrice>
			<premierDate>15-11-2018</premierDate>
			<metariticRate>
				<metascore>81</metascore>
				<userScore>2.8</userScore>
				<numberOfVotes>2269</numberOfVotes>
			</metariticRate>		
			<cover src = "covers/battlefield5.jpg"/>
		</game>
		
		<game producerID = "CD" engineID = "Frostbite" publisherID = "SE" ratingID = "M" platformID = "Multi" genreID="Action">
			<title>Shadow of the Tomb Raider</title>
			<description>Experience Lara Croft's defining moment as she becomes the Tomb Raider. In Shadow of the Tomb Raider, Lara must master a deadly jungle, overcome terrifying tombs, and persevere through her darkest hour. As she races to save the world from a Maya apocalypse, Lara will ultimately be forged into the Tomb Raider she is destined to be. </description>
			<premierPrice currency = "PLN">249.90</premierPrice>
			<premierDate>14-10-2018</premierDate>
			<metariticRate>
				<metascore>77</metascore>
				<userScore>6.9</userScore>
				<numberOfVotes>460</numberOfVotes>
			</metariticRate>		
			<cover src = "covers/tombRider.jpg"/>
		</game>
		
		<game producerID = "BW" engineID = "EclipseEngine" publisherID = "EA" ratingID = "M" platformID = "Multi" genreID="RPG">
			<title>Dragon Age Origins</title>
			<description>Dragon Age: Origins is a role-playing game developed by BioWare and published by Electronic Arts. ... BioWare described Dragon Age: Origins as a "dark heroic fantasy" set in a unique world, and a spiritual successor to their previous Baldur's Gate and Neverwinter Nights franchises.</description>
			<premierPrice currency = "PLN">139.90</premierPrice>
			<premierDate>3-11-2007</premierDate>
			<metariticRate>
				<metascore>91</metascore>
				<userScore>8.7</userScore>
				<numberOfVotes>3978</numberOfVotes>
			</metariticRate>		
			<cover src = "covers/dao.jpg"/>
		</game>
		
		<game producerID = "BW" engineID = "Unreal" publisherID = "EA" ratingID = "M" platformID = "Multi" genreID="RPG">
			<title>Mass Effect</title>
			<description>Mass Effect is a science-fiction action-role-playing third-person-shooter video-game series developed by the Canadian company BioWare and released for the Xbox 360, PlayStation 3, and Microsoft Windows, with the third instalment also released on the Wii U.</description>
			<premierPrice currency = "PLN">129.90</premierPrice>
			<premierDate>28-05-2008</premierDate>
			<metariticRate>
				<metascore>89</metascore>
				<userScore>8.6</userScore>
				<numberOfVotes>2999</numberOfVotes>
			</metariticRate>		
			<cover src = "covers/mass.jpg"/>
		</game>
	</games>
</GamesCatalog>