=== JuliuszGasecki/PKCK/Zadanie2/zadanie2_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:myType="http://www.foo.com"
targetNamespace="http://www.foo.com"
elementFormDefault="qualified">

<!--
ROOT
 -->
	<xs:element name="GamesCatalog" type="myType:t_GamesCatalog">

		<xs:key name="producer_key">
			<xs:selector xpath=".//myType:producer"/>
			<xs:field xpath="@producerID"/>
		</xs:key>
		<xs:keyref name="producerRefkey" refer="myType:producer_key">
			<xs:selector xpath=".//myType:game"/>
			<xs:field xpath="@producerID"/>
		</xs:keyref>

		<xs:key name="engine_key">
			<xs:selector xpath=".//myType:engine"/>
			<xs:field xpath="@engineID"/>
		</xs:key>
			<xs:keyref name="engineRefkey" refer="myType:engine_key">
			<xs:selector xpath=".//myType:game"/>
			<xs:field xpath="@engineID"/>
		</xs:keyref>
	
		<xs:key name="publisher_key">
			<xs:selector xpath=".//myType:publisher"/>
			<xs:field xpath="@publisherID"/>
		</xs:key>
		<xs:keyref name="publisherRefkey" refer="myType:publisher_key">
			<xs:selector xpath=".//myType:game"/>
			<xs:field xpath="@publisherID"/>
		</xs:keyref>
		
		<xs:key name="Rating_key">
			<xs:selector xpath=".//myType:Rating"/>
			<xs:field xpath="@ratingID"/>
		</xs:key>
		<xs:keyref name="RatingRefkey" refer="myType:Rating_key">
			<xs:selector xpath=".//myType:game"/>
			<xs:field xpath="@ratingID"/>
		</xs:keyref>
		
		<xs:key name="platform_key">
			<xs:selector xpath=".//myType:platform"/>
			<xs:field xpath="@platformID"/>
		</xs:key>
		<xs:keyref name="platformRefkey" refer="myType:platform_key">
			<xs:selector xpath=".//myType:game"/>
			<xs:field xpath="@platformID"/>
		</xs:keyref>
		
		<xs:key name="genre_key">
			<xs:selector xpath=".//myType:genre"/>
			<xs:field xpath="@genreID"/>
		</xs:key>
		<xs:keyref name="genreRefkey" refer="myType:genre_key">
			<xs:selector xpath=".//myType:game"/>
			<xs:field xpath="@genreID"/>
		</xs:keyref>
	</xs:element>
	
	<xs:complexType name="t_GamesCatalog">
		<xs:sequence>
			<xs:element name="header" type="myType:t_header"/>
			<xs:element name="producers" type="myType:t_producers"/>
			<xs:element name="gameEngines" type="myType:t_gameEngines"/>
			<xs:element name="publishers" type="myType:t_publishers"/>
			<xs:element name="Ratings" type="myType:t_Ratings"/>
			<xs:element name="platforms" type="myType:t_platforms"/>
			<xs:element name="genres" type="myType:t_genres"/>
			<xs:element name="games" type="myType:t_games"/>
		</xs:sequence>
    </xs:complexType>

	<xs:complexType name="t_header">
		<xs:sequence>
			<xs:element name="polskieZnakiŹŻ"/>
			<xs:element name="titleOfProject" type="xs:string"/>
			<xs:element name="description" type="xs:string"/>
			<xs:element name="authors" type="myType:t_authors"/>
			<xs:element name="modificationDate" type="myType:t_modificationDate"/>
			<xs:element name="university" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name = "t_modificationDate">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{2}[/.-]\d{2}[/.-]\d{4}"></xs:pattern>
            <xs:length value="10"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="t_authors">
		<xs:sequence>
			<xs:element name="student" minOccurs="1" maxOccurs="2" type="myType:t_student"/>
		</xs:sequence>
	</xs:complexType>
  
	<xs:complexType name="t_student">
		<xs:sequence>
			<xs:element name="firstName" type="myType:t_firstName"/>
			<xs:element name="lastName" type="myType:t_lastName"/>
			<xs:element name="index" type="myType:t_index"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:simpleType name="t_firstName">
		<xs:restriction base="xs:string">
			<xs:pattern value="([A-Z](([a-z])*))"/>
			      <xs:maxLength value="50"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="t_lastName">
		<xs:restriction base="xs:string">
			<xs:pattern value="([\p{Lu}])([\p{Ll}])*(([-\s])([\p{Lu}])([\p{Ll}])*)?"/>
			<xs:maxLength value="50"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="t_index">
		<xs:restriction base="xs:integer">
			<xs:pattern value="[0-9]{6}"/>
		</xs:restriction>
	</xs:simpleType> 
	
	<xs:complexType name="t_producers">
			<xs:sequence>
				<xs:element name="producer" minOccurs="1" maxOccurs="unbounded" type="myType:t_producer"/>
			</xs:sequence>
	</xs:complexType>
		
	<xs:complexType name="t_producer">
		<xs:sequence>
			<xs:element name="companyName" type="myType:t_restrictedString"/>
			<xs:element name="foundationDate" type="myType:t_foundationDate"/>
			<xs:element name ="sharePrice" type="myType:t_sharePrice"/>	
			<xs:element name="headquarters" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="producerID">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:whiteSpace value="preserve"/>
					<xs:minLength value="2"/>
					<xs:maxLength value="20"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	
	<xs:simpleType name="t_restrictedString">
		<xs:restriction base="xs:string">
					<xs:whiteSpace value="preserve"/>
					<xs:minLength value="2"/>
					<xs:maxLength value="50"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="t_foundationDate">
		<xs:restriction base="xs:integer">
			<xs:pattern value="[1-2][0-9][0-9][0-9]"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="t_sharePrice">
		<xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="currency" default="USD">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="USD"/>
							<xs:enumeration value="PLN"/>
							<xs:enumeration value="EURO"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
  

	<xs:complexType name="t_gameEngines">
		<xs:sequence>
			<xs:element name="engine" minOccurs="1" maxOccurs="unbounded" type="myType:t_engine"/>
		</xs:sequence>
	</xs:complexType>	
	
	<xs:complexType name="t_engine">
		<xs:sequence>
			<xs:element name="name" type="myType:t_restrictedString"/>
			<xs:element name="company" type="myType:t_restrictedString"/>
		</xs:sequence>
			<xs:attribute name="engineID" use="required" type="myType:t_restrictedString"/>
			<xs:attribute name="programmingLanguage" use="optional"  type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="t_publishers">
		<xs:sequence>
			<xs:element name="publisher" minOccurs="1" maxOccurs="unbounded" type="myType:t_publisher"/>
		</xs:sequence>
	</xs:complexType>	
	
	
	<xs:complexType name="t_publisher">
		<xs:sequence>
			<xs:element name="publisherName" type="myType:t_restrictedString"/>
		</xs:sequence>
		<xs:attribute name="publisherID" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:whiteSpace value="preserve"/>
					<xs:minLength value="2"/>
					<xs:maxLength value="20"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="t_Ratings">
		<xs:sequence>
			<xs:element name="Rating" minOccurs="1" maxOccurs="unbounded" type="myType:t_Rating"/>
		</xs:sequence>
	</xs:complexType>
	

	<xs:complexType name="t_Rating">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="ratingID" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="A"/>
							<xs:enumeration value="M"/>
							<xs:enumeration value="T"/>
							<xs:enumeration value="E"/>
							<xs:enumeration value="EC"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="t_platforms">
		<xs:sequence>
			<xs:element name="platform" minOccurs="1" maxOccurs="unbounded" type="myType:t_platform"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="t_platform">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="platformID" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="PC"/>
							<xs:enumeration value="PS4"/>
							<xs:enumeration value="XBOX"/>
							<xs:enumeration value="Multi"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	
	<xs:complexType name="t_genres">
		<xs:sequence>
			<xs:element name="genre" minOccurs="1" maxOccurs="unbounded" type="myType:t_genre"/>
		</xs:sequence>
	</xs:complexType>	
	
	<xs:complexType name="t_genre">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="genreID" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="RPG"/>
							<xs:enumeration value="FPS"/>
							<xs:enumeration value="Stealth"/>
							<xs:enumeration value="RTS"/>
							<xs:enumeration value="Action"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>	
 
	<xs:complexType name="t_games">
		<xs:sequence>
			<xs:element name="game" minOccurs="0" maxOccurs="unbounded" type="myType:t_game"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="t_game">
		<xs:sequence>
			<xs:element name="title" type="myType:t_restrictedString"/>
			<xs:element name="description" type="xs:string"/>
			<xs:element name="premierPrice" type="myType:t_premierPrice"/>
			<xs:element name="premierDate" type="myType:t_premierDate"/>
			<xs:element name="metariticRate" type="myType:t_metariticRate"/>
			<xs:element name="cover" type="myType:t_cover"/>
		</xs:sequence>
	<xs:attributeGroup ref="myType:gameAtrGroup"/>
 	</xs:complexType>
	
	<xs:attributeGroup name="gameAtrGroup">
		<xs:attribute name="producerID" use="required" type="xs:string"/>
		<xs:attribute name="engineID" use="required" type="xs:string"/>
		<xs:attribute name="publisherID" use="required" type="xs:string"/>
		<xs:attribute name="ratingID" use="required" type="xs:string"/>
		<xs:attribute name="platformID" use="required" type="xs:string"/>
		<xs:attribute name="genreID" use="required" type="xs:string"/>
	</xs:attributeGroup>

	<xs:complexType name="t_cover">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="src" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:simpleType name="t_premierDate">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-3][0-9][-.][0-1][0-9][-.][0-9]{4}"/>
		</xs:restriction>
	</xs:simpleType>	
	
	<xs:complexType name="t_premierPrice">
		<xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="currency" default="PLN">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="USD"/>
							<xs:enumeration value="PLN"/>
							<xs:enumeration value="EURO"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="t_metariticRate">
		<xs:sequence>
			<xs:element name="metascore" type ="myType:t_metascore"/>
			<xs:element name="userScore" type="myType:t_userScore"/>
			<xs:element name="numberOfVotes" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:simpleType name="t_metascore">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="100"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="t_userScore">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="10"/>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== JuliuszGasecki/PKCK/Zadanie2/TEST.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="style.css"?>

<GamesCatalog
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="urn:Test.Namespace"
xsi:schemaLocation="urn:Test.Namespace zadanie2_schema.xsd">

	<header>
		<polskieZnakiŹŻ/>
		<titleOfProject>Games Catalog</titleOfProject>
		<description>The best games of the last 15 years!</description>
		<authors>
			<student>
				<firstName>Juliusz</firstName>
				<lastName>Gąsecki</lastName>
				<index>210184</index>
			</student>
			<student>
				<firstName>Bartosz</firstName>
				<lastName>Stempień</lastName>
				<index>210327</index>
			</student>
		</authors>
		<modificationDate>17-03-2019</modificationDate>
		<university>Politechnika Łódzka Wydział Fizyki Technicznej, Informatyki i Matematyki Stosowanej</university>
	</header>
	
	<producers>
		<producer producerID="BW">
			<companyName>BioWare</companyName>
			<foundationDate>1995</foundationDate>
			<sharePrice currency="USD">98.36 </sharePrice>
			<headquarters>Edmonton</headquarters>	
		</producer>
		<producer producerID="CDP">
			<companyName>CD Project Red</companyName>
			<foundationDate>1994</foundationDate>
			<sharePrice currency="PLN">185.90</sharePrice>
			<headquarters>Warszwa</headquarters>	
		</producer>
		<producer producerID="Bethesda">
			<companyName>Bethesda Softworks</companyName>
			<foundationDate>1986</foundationDate>
			<sharePrice currency="USD">78.34</sharePrice>
			<headquarters>Rockville</headquarters>	
		</producer>
		<producer producerID="CD">
			<companyName>Crystal Dynamics</companyName>
			<foundationDate>1992</foundationDate>
			<sharePrice currency="USD">87.32</sharePrice>
			<headquarters>Redwood City</headquarters>	
		</producer>
		<producer producerID="Ubisoft">
			<companyName>Ubisof</companyName>
			<foundationDate>1986</foundationDate>
			<sharePrice currency="EURO">79.50</sharePrice>
			<headquarters>Montreuil</headquarters>	
		</producer>
		<producer producerID="Activision">
			<companyName>Activision Inc.</companyName>
			<foundationDate>1979</foundationDate>
			<sharePrice currency="USD">87.90</sharePrice>
			<headquarters>Santa Monica</headquarters>	
		</producer>
		<producer producerID="Dice">
			<companyName>EA Digital Illusions Creative Entertainment</companyName>
			<foundationDate>1992</foundationDate>
			<sharePrice currency="USD">97.54</sharePrice>
			<headquarters>Stockholm</headquarters>	
		</producer>		
		<producer producerID="Insomniac">
			<companyName>Insomniac Games</companyName>
			<foundationDate>1994</foundationDate>
			<sharePrice currency="USD">69.84</sharePrice>
			<headquarters>Burbank</headquarters>	
		</producer>		
		<producer producerID="Maxis">
			<companyName>Maxis Games</companyName>
			<foundationDate>1987</foundationDate>
			<sharePrice currency="USD">56.90</sharePrice>
			<headquarters>Redwood Shores</headquarters>	
		</producer>
	</producers>
	
	<gameEngines>
		<engine engineID = "Frostbite" programmingLanguage = "C++">
			<name>Frostbite</name>
			<company>EA Dice</company>
		</engine>
		
		<engine engineID = "FEngine" programmingLanguage = "C++">
			<name>Foundation engine</name>
			<company>Crystal Dynamics</company>
		</engine>
		
		<engine engineID = "EclipseEngine" programmingLanguage = "C++">
			<name>Eclipse engine</name>
			<company>EclipseOrigins</company>
		</engine>
		<engine engineID = "Unreal" programmingLanguage = "C++">
			<name>Unreal engine</name>
			<company>Epic Games</company>
		</engine>
		<engine engineID = "CE" programmingLanguage = "C++">
			<name>Creation Engine</name>
			<company>Bethesda Games Studios</company>
		</engine>
		<engine engineID = "Anvil" programmingLanguage = "C++">
			<name>Anvil</name>
			<company>Ubisof</company>
		</engine>		
		<engine engineID = "REDengine" programmingLanguage = "C++">
			<name>REDengine</name>
			<company>CD Project Red</company>
		</engine>
	</gameEngines>
	
</GamesCatalog>
